apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  namespace: web
  labels:
    app: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angular
          image: azizbk9/angular-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: angular-config
                  key: api_url
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
  namespace: web
  labels:
    app: angular
spec:
  ports:
    - nodePort: 30177
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: angular
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: angular-config
  namespace: web
data:
  api_url: "http://192.168.49.2:30762"
